=== davidsneighbour/kollitsch.dev/data/dnb/kollitsch/music.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "slug": {
        "type": "string",
        "description": "A unique identifier for the entity."
      },
      "name": {
        "type": "string",
        "description": "The name of the entity."
      },
      "link": {
        "type": "string",
        "format": "uri",
        "description": "The main URL associated with the entity."
      },
      "description": {
        "type": "string",
        "description": "A description of the entity."
      },
      "links": {
        "type": "object",
        "description": "An optional object containing additional predefined social media links.",
        "properties": {
          "twitter": {
            "type": "string",
            "format": "uri",
            "description": "URL to the Twitter profile."
          },
          "instagram": {
            "type": "string",
            "format": "uri",
            "description": "URL to the Instagram profile."
          },
          "website": {
            "type": "string",
            "format": "uri",
            "description": "URL to the official website.",
            "minLength": 1
          },
          "facebook": {
            "type": "string",
            "format": "uri",
            "description": "URL to the Facebook profile."
          },
          "tiktok": {
            "type": "string",
            "format": "uri",
            "description": "URL to the TikTok profile."
          }
        },
        "required": ["website"],
        "additionalProperties": false
      }
    },
    "required": ["slug", "name", "description"],
    "additionalProperties": false,
    "oneOf": [{ "required": ["link"] }, { "required": ["links"] }]
  }
}

=== davidsneighbour/kollitsch.dev/data/dnb/kollitsch/music.json
[
  {
    "slug": "ben-lukas-boysen",
    "name": "Ben Lukas Boysen",
    "link": "https://benlukasboysen.com/",
    "description": "Ben Lukas Boysen, also known by his stage name Hecq, is an electronic music composer based in Berlin. (via Wikipedia)"
  },
  {
    "slug": "chromatics",
    "name": "Chromatics",
    "link": "https://soundcloud.com/chromaticsofficial",
    "description": ""
  },
  {
    "slug": "dannykreutzfeldt",
    "name": "Danny Kreutzfeldt",
    "link": "https://www.discogs.com/artist/27424-Danny-Kreutzfeldt",
    "description": "Danny Kreutzfeldt covered a wide range of styles from deep ambient dub to vast harshnoise soundscapes and went on to perform, collaborate and release under numerous monikers before discontinuing most of these activities around 2008."
  },
  {
    "slug": "khruangbin",
    "name": "Khruangbin",
    "link": "https://twitter.com/Khruangbin",
    "description": "Khruangbin (/ˈkrʌŋbɪn/ KRUNG-bin; Thai: [kʰrɯa̯ŋ˥˩.bin], เครื่องบิน) is an American musical trio from Houston, Texas. The band comprises Laura Lee on bass, Mark Speer on guitar, and Donald Ray \"DJ\" Johnson Jr. on drums. "
  },
  {
    "slug": "nineinchnails",
    "name": "Nine Inch Nails",
    "link": "https://www.nin.com/",
    "description": ""
  },
  {
    "slug": "irisarri",
    "name": "Rafael Anton Irisarri",
    "link": "https://www.irisarri.org/",
    "description": ""
  },
  {
    "slug": "rammstein",
    "name": "Rammstein",
    "link": "https://www.rammstein.de/en/",
    "description": "Rammstein is a German Neue Deutsche Härte band formed in Berlin in 1994."
  },
  {
    "slug": "queensryche",
    "name": "Queensrÿche",
    "link": "https://en.wikipedia.org/wiki/Queensr%C3%BFche",
    "description": "Queensrÿche has sold over 20 million albums worldwide, including over 6 million albums in the United States. They are considered one of the leaders of the progressive metal scene of the mid-to-late 1980s, and often referred to as one of the \"Big Three\" of the genre."
  }
]
